### ISSUE TITLE
readme.mdに「* Alt単発押しで」

### ISSUE THREAD

**Issue by imamurayusuke** [swanmatch/jiskb_evoluter#1]
https://github.com/swanmatch/jiskb_evoluter/blame/27f6c8d0cf37511dff9a830d7f0f0e4fae152ea6/readme.md#L25

に「* Alt単発押しで」とだけ書かれた行があって続きが気になります

**Comment by swanmatch** [comment]
変なコミットしちゃってたみたいですね。
直しました！
